# Generated by Django 5.0.6 on 2024-12-08 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_transactionmaster_batchid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionmaster',
            old_name='batchId',
            new_name='batchID',
        ),
    ]
