# Generated by Django 5.0.6 on 2024-12-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_batchid_transactionmaster_batchid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmaster',
            name='batchID',
            field=models.CharField(choices=[(' ', 'Select_Batch'), ('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028'), ('2028-2029', '2028-2029'), ('2029-2030', '2029-2030')], default=' ', max_length=10),
        ),
    ]
