# Generated by Django 5.1.4 on 2025-01-01 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_transactionmaster_batchid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmaster',
            name='committeeDesignation',
        ),
        migrations.RemoveField(
            model_name='transactionmaster',
            name='committeeName',
        ),
        migrations.RemoveField(
            model_name='transactionmaster',
            name='designation',
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Issued', 'Issued')], default='Pending', max_length=10)),
                ('certificate_id', models.CharField(max_length=20, unique=True)),
                ('certificate_title', models.CharField(blank=True, max_length=100)),
                ('issued_by', models.CharField(blank=True, max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='app1.studentmaster')),
            ],
        ),
        migrations.DeleteModel(
            name='CommitteeDepartment',
        ),
        migrations.DeleteModel(
            name='CommitteeMaster',
        ),
        migrations.DeleteModel(
            name='StaffMaster',
        ),
        migrations.DeleteModel(
            name='TransactionMaster',
        ),
    ]
