# Generated by Django 5.1.4 on 2025-01-01 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_transactionmaster_committeedesignation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
