# Generated by Django 5.1.4 on 2025-01-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_type',
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
