# Generated by Django 5.1.4 on 2025-01-01 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_certificate_certificate_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificateType', models.CharField(max_length=50)),
                ('issueDate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Issued', 'Issued'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='app1.studentmaster')),
            ],
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
