# Generated by Django 5.0.6 on 2025-01-03 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_certificatemaster_delete_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('issueDate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Issued', 'Issued'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('batchNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app1.batchmaster')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app1.semestermaster')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app1.studentmaster')),
            ],
            options={
                'unique_together': {('student', 'batchNo', 'semester', 'marks', 'issueDate')},
            },
        ),
    ]
